services:
  - type: web
    name: printsmithllc-website
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/printsmithllc/website
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production